# Site settings
title: A blog about lorem ipsum dolor sit amet
description: A blog about lorem ipsum dolor sit amet
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Miguel Torres
user_description: Junior Back End Developer focused on Ruby on Rails. Familiarity working with API’s, PostgreSQL, webpacker, JavaScript, and Vue.js
user_title: Software Developer
email: migueltg93@gmail.com
twitter_username: @mickeytgl
github_username:  mickeytgl
gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
